### ISSUE TITLE
nc2waves.py and atmos_correct from utils.py

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#142]
Hi Dan,

I have two quick questions: 

1. Could you please add: `import xarray as xr` and `import numpy as np` to beginning of nc2waves.py? Those are needed when handling continuous data and using def make_wave_bursts. 

2. Would you be ok with adding the reindexing by nearest method and 10-min tolerance back for atmos_correct?

I am noticing that when processing continuous dwave data, the atmospheric pressure correction is not working properly. Over at the WH office, we are using a Jupyter Notebook to create the atmpres.cdf file and Jupyter Notebook is not able to create a reindexed .cdf file on the 4hz continuous time base (at least in a reasonable time). I have been relying on the run script to do the re-indexing using nearest method. 

I see how this can be a possible issue because most atmpres.cdf files are reindexed when created in Jupyter Notebook. So, that atmospheric pressure data will be reindexed twice, but I don't think the second reindex by the script would actually change the time if it's already been matched up in the Jupyter Notebook, right? One way to avoid this would be add an `if` `elif` statement to atmos_correct that will only re-index if the data is from a continuous dwave. All other atmpres.cdf files will be not be reindexed. 

Hopefully all this made sense, if not I can elaborate...

Thanks

**Comment by ssuttles-usgs** [comment]
Try adding this line in the jupyter notebook before doing the reindexing.

atm = atm.chunk(chunks={"time": 200000})




Steven Suttles
U. S. Geological Survey, Woods Hole Coastal and Marine Science Center
384 Woods Hole Road, Woods Hole, MA 02543-1598
***@***.******@***.***>
(508) 457-2228 (o)
(508) 524-5871 (c)
________________________________
From: rbales-usgs ***@***.***>
Sent: Tuesday, August 15, 2023 2:39 PM
To: USGS-CMG/stglib ***@***.***>
Cc: Suttles, Steven E ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [USGS-CMG/stglib] nc2waves.py and atmos_correct from utils.py (Issue #142)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Steve,
I don't think I know how to chunk in the data. Can you send me a Jupyter Notebook with an example?

**Comment by rbales-usgs** [comment]
Hi Dan, 

PR has been submitted for point #1. 
Steve showed me how to create a atmpres.cdf file that is reindexed to continuous dwave time base through chunking. So, as of now, I don't think point 2 needs to be addressed. But I will raise an issue if anything changes...

Thanks!

**Comment by dnowacki-usgs** [comment]
Closed by #143
