### ISSUE TITLE
cutoff_ampl feature for aqd

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#144]
Hi Dan,

I've got some AQD data that was affected by periods of burial from marsh material. During burial periods the amplitude/AGC is low and I tried using a cutoff_ampl threshold to fill these periods or burial, but it didn't seem to work. I also couldn't find a def in the AQD cdf2nc.py or aqdutils.py that would fill data by an AGC threshold. Is this located somewhere that I am overlooking? 

If it is not in stglib, could I add this function to aqdutils.py as a QAQC option? 

Thanks, 
Bo

**Comment by dnowacki-usgs** [comment]
Yes, that would be great!

**Comment by rbales-usgs** [comment]
Great, I will work on that. 

I will also include a QAQC feature that will remove additional surface bins from AQD data. I am working with data that has bad velocities in the top 1 or 2 surface bins even after using trim_method 'water level sl.' This feature will allow the user to specify additional surface bins to fill if 'water level sl' was not sufficient.

**Comment by dnowacki-usgs** [comment]
Fixed by #145
