### ISSUE TITLE
Dwave test zipped folder

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#146]
Hi Dan, 

Merge 143 included a continuous dwave test. Because the data is in a zipped folder, it is being unzipped during the test and git is wanting to track the unzipped folder. I guess the only way around this is to submit a PR with the unzipped folder included in the stglib test data folder? 

-Bo

**Comment by dnowacki-usgs** [comment]
Add the unzipped folder to `.gitignore`

**Comment by dnowacki-usgs** [comment]
Closing this. Please reopen if the .gitignore solution did not work.
