### ISSUE TITLE
where do run scripts live?

### ISSUE THREAD

**Issue by rmallen86** [USGS-CMG/stglib#149]
I have been looking for runvecdat2cdf.py.  It is mentioned in the documentation, but I can't find it on the repository.  I want to process data from a Nortek vector, specifically including analog outputs.  But first, I need to find this file.  Thank you!

**Comment by dnowacki-usgs** [comment]
The run scripts are generated by the installation process and added to the system path, so you no longer need to specify the path. Are you sure you are running the latest version?

**Comment by rmallen86** [comment]
I think I am!  I don't see the scripts on the github repository either.  Specifically, we were trying to make sure that a Nortek vector processed through stglib output the data recorded as "anin1", and we wanted to check the run script.

**Comment by rmallen86** [comment]
So, this is an answer to the question above "where do run scripts live?"  
they live here:
https://github.com/USGS-CMG/stglib/blob/master/stglib/core/runcmd.py

Thanks for pointing me in this direction, Dan, and I'll try and figure out my vector question separately
