### ISSUE TITLE
drop_vars functionality in other instruments?

### ISSUE THREAD

**Issue by rmallen86** [USGS-CMG/stglib#151]
The EXO seems to have the ability to remove outputs from the final nc file, via the "drop_vars" keyword in the config file:
https://stglib.readthedocs.io/en/latest/config.html#exo

Could that function be added to other instruments?  Specifically, I'd like to output a vector file that does not include velocities - we used the vector simply to log data from an external sensor (the LISST-ABS), so we want the AnalogInput field, but not the velocities.

**Comment by dnowacki-usgs** [comment]
See PR #152
