### ISSUE TITLE
add capability to specify pressure sensor height for a vector

### ISSUE THREAD

**Issue by rmallen86** [USGS-CMG/stglib#181]
Vectors can be oriented horizontally or vertically (up or down), and they can have internal or external pressure sensors.  I think it may be useful to specify the pressure sensor height above bed along side the vector head.  Perhaps we can add a key to the yaml file along the lines of "pressure_sensor_height"?

**Comment by ssuttles-usgs** [comment]
Looking back to processing Marinna did for our dataset from Matanzas Inlet in 2018, she used these 2 attributes in the old matlab SVN code to specify the probe and pressure sensor height for cabled vector deployments.

metadata.pressure_sensor_height =  2.008;  % m
metadata.probe_height = 0.553; % m

I suggest we implement something similar in stglib. We routinely deploy cabled vectors where the heights of the corresponding pressure data needs to be specified in addition to the velocity probe (or measurement volume) height. In fact, we have a couple of datasets in the processing queue with cabled vectors.

**Comment by dnowacki-usgs** [comment]
I'm checking in with PCMSC folks to see if they used the same nomenclature in their Matlab scripts. I wonder if probe_height is the preferred way to specify the height. Should it be sample volumes height?

Would we then have a z coordinate variable with two values, one for pressure and one for probe sample volume, and then index the appropriate variables by time, z?

**Comment by ssuttles-usgs** [comment]
I think you would need a second height coordinate variable, right? maybe 'zp'?  or alternately have a vertical offset attribute in the pressure variable? Not sure what is better.

**Comment by dnowacki-usgs** [comment]
PCMSC uses the same nomenclature in the Matlab scripts.

metadata.pressure_sensor_height =  0.62;                          
metadata.probe_height = 0.40; %vec cmab on frame %not sv

Note that specifies height of probe and not SV. What's the best approach here? [probe or SV?]

**Comment by dnowacki-usgs** [comment]
I think it's better to specify the pressure sensor height and the sample volume height [not probe height] for velocity. So I propose `pressure_sensor_height` and `velocity_sample_volume_height` as the attrs to specify these.

**Comment by dnowacki-usgs** [comment]
This has been included in #186, so closing this issue now.
