### ISSUE TITLE
Error in create_z

### ISSUE THREAD

**Issue by kurt-rosenberger** [USGS-CMG/stglib#248]
Hey Dan
I think there is an error in utils.create_z - I have a dataset from Solinst CTD that I'm trying to make netCDF files from, and it has the D_3 variable in it. In create_z, it checks for D_3, but then tries to do a mean on P1_ac - seems like this is just a typo? Could we fix that? I think its on line 1021.

Thx
Kurt

**Comment by dnowacki-usgs** [comment]
At first glance, yes it does look like a typo. Want to take a stab at your first pull request?

**Comment by dnowacki-usgs** [comment]
For tiny edits like this you should be able do it all on GitHub. Go to the file in question, click the pencil icon in top right corner, make your edits, click create a new branch and start a pull request.

**Comment by kurt-rosenberger** [comment]
OK, I'll give that a shot. Thanks

**Comment by kurt-rosenberger** [comment]
Its telling me I have to fork it, and I want to make sure I do that right

**Comment by ssuttles-usgs** [comment]
Kurt,

Yes, I see that in the else: part of that section of code. Good catch and welcome to the stglib contributor community!!

-steve



Steven Suttles
U. S. Geological Survey, Woods Hole Coastal and Marine Science Center
384 Woods Hole Road, Woods Hole, MA 02543-1598
***@***.******@***.***>
(508) 457-2228 (o)
(508) 524-5871 (c)
________________________________
From: kurt-rosenberger ***@***.***>
Sent: Tuesday, August 6, 2024 3:01 PM
To: USGS-CMG/stglib ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [USGS-CMG/stglib] Error in create_z (Issue #248)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hey Dan
I think there is an error in utils.create_z - I have a dataset from Solinst CTD that I'm trying to make netCDF files from, and it has the D_3 variable in it. In create_z, it checks for D_3, but then tries to do a mean on P1_ac - seems like this is just a typo? Could we fix that? I think its on line 1021.

Thx
Kurt
