### ISSUE TITLE
RBR Virtuoso Tu data handling needed

### ISSUE THREAD

**Issue by mmartini-usgs** [USGS-CMG/stglib#43]
The RSK section of code is specific to the RBR DWave and burst data.  The Virtuoso Tu has different field names, sampling types, etc. in the raw data file that need to be handled differently than the code is currently structured.  

I propose separate files to handle DWave and Virtuoso-Tu data as they are so different.

**Comment by dnowacki-usgs** [comment]
Lots has changed in the past three years and we now support turbidity and other types of data from Virtuoso instruments. Closing this now.
