### ISSUE TITLE
Clock drift correction needs fixing.

### ISSUE THREAD

**Issue by ssuttles-usgs** [USGS-CMG/stglib#44]
I tried a clock drift correction when processing some Aquadopp data (mean currents only). The drift correction (+15 sec) was applied to the time units attribute in the -raw.cdf file as an offset. Then when trying to do atmospheric correction (ac) to pressure data in the nc file creation it failed because there was a mismatch between time between 'atmpres' variable from atmpres.cdf and 'Pressure' in aqd-raw.cdf file.  Here is link to files;

https://github.com/ssuttles-usgs/stglib/tree/clockerr_issue/clockerr_issue

Also the clock drift should be applied as a linear correction between the time the clock was set before the deployment and when it was checked after recovery. Not a simple offset.

**Comment by ssuttles-usgs** [comment]
Note: the ClockError was set in the config.yaml file. When I changed it to 0, the code worked fine, including the ac.

**Comment by dnowacki-usgs** [comment]
Thanks Steve. Made a change that linearly interpolates time to the ClockError value. Could you please re-run and see if this fixes the issue?

**Comment by ssuttles-usgs** [comment]
Great! What files have changed? I checked your master repo and I did not
see any new commits. I tried syncing and there were a few files that are
now showing today's date in my local forked master;

scripts/ aqd_make_press_ac.ipynb
scripts/dw_make_press_ac.ipynb
stglib/aqd/cdf2nc.py
examples/atmpres.cdf
examples/gndcrmet.nc

Are those the changes? I am not quite clear on the best way to get the
changes on the upstream master to my local forked master. I was also
puzzled that I did not see anything new on your upstream master. This is it
right?

https://github.com/dnowacki-usgs/stglib

Work in progress for me figuring out how all of this works. Happy 4th!!



Steven Suttles
U. S. Geological Survey, Coastal and Marine Geology
384 Woods Hole Road, Woods Hole, MA 02543-1598
ssuttles@usgs.gov
(508) 457-2228

**Comment by dnowacki-usgs** [comment]
If you check out the issue on GH you can see the files that have changed in the branch `fix-clockerr`. [This link shows the diffs](https://github.com/dnowacki-usgs/stglib/commit/084e2a897237e74d202c76d88e85dde7e325a26d). Also, when you reply to an email from GH, it gets posted to the issue online. Happy 4th. :fireworks:

**Comment by dnowacki-usgs** [comment]
@ssuttles-usgs Can you confirm clock drift code is doing what we expect now? Trying to clean up some old issues.
