### ISSUE TITLE
KORexo file version issues 

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#55]
Alex and I are processing exo data. 

When running runexocsv2cdf.py, Python raises an error message stating, `KeyError: 'KOR Export File'`.

This error message is generated when the read_exo_header function is called (defined in exo.py). 
The read_exo_header function is written to read both old and new KOR export files and uses a 'try and except' statement. 
However, the 'KeyError' exception is not included and Python stops running. 
By replacing `except pd.ParserError` with `except KeyError` after the 'old KOR file' block, read_exo_header will fully run. 

More KeyErrors are generated when the read_exo function (defined in exo.py) applies sensor serial numbers to each sensor. 
These errors are raised because of differences in variable names between the old and new KOR file versions. 
By adding a few 'try and except' statements with variable names corresponding to the new KOR files, no errors are generated when calling the read_exo function. 

I think these changes are more of a temporary fix and hope to receive some feedback about how to properly modify these functions.

Thanks! 
Bo

**Comment by dnowacki-usgs** [comment]
Thanks for the report @rbales-usgs. Can you attach a CSV that fails and also the yaml config file you are using?

**Comment by dnowacki-usgs** [comment]
This should be fixed in 0.2.2. @rbales-usgs, please reopen if not.
