### ISSUE TITLE
downloading stglib following the "easy (local machine)" strategy doesn't give all the updates

### ISSUE THREAD

**Issue by rmallen86** [USGS-CMG/stglib#64]
I tried downloading stglib on Aug 2, 2022, and today (Aug 10) I tried using two codes from Scripts (runecocsv2cdf.py and runecocdf2nc.py).  runecocdf2nc.py uses utils.py. 

My version of utils.py has 1195 lines, and line 1008 reads
  "deltat = np.asscalar((ds["time"][1] - ds["time"][0]) / np.timedelta64(1, "s"))".  Python told me that the "asscalar" was a problem.  I think this has already been fixed, as the version of utils.py on github has 1278 lines, and line 1089 (the new location of the add_delta_t function) no longer requires "asscalar".

My conclusion (really Steve's because he was helping me) is that in downloading and setting up with conda I didn't get the updates, since utils.py says it was updated 28 days ago.  Might there be an issue here?

**Comment by dnowacki-usgs** [comment]
This is happening because Conda only has the latest release (0.4.0 released on May 31), but not any changes that have been committed to the repo since the release date. If you want to use the latest changes, you should [clone locally by following these instructions](https://stglib.readthedocs.io/en/latest/install.html#if-you-want-to-contribute-to-stglib-development).

**Comment by rmallen86** [comment]
Thanks, that's what I did, and it seemed to work.  I should have updated with that information; I'm glad it's consistent with what you say.  Might I suggest a note in those help pages that addresses this?  LMK if you'd like me to draft.

**Comment by dnowacki-usgs** [comment]
Yeah! That would be awesome if you'd like to take a stab at updating the docs. You can edit them in the repo and create a pull request. [Docs are here](https://github.com/USGS-CMG/stglib/tree/master/doc).

**Comment by dnowacki-usgs** [comment]
Pinging @rmallen86  :)

**Comment by rmallen86** [comment]
Thanks for the reminder!  I added some text but I forgot to put in a comment...

**Comment by dnowacki-usgs** [comment]
I'm going to close this issue for now. If you want to make updates or changes, please reopen. Thanks!
