### ISSUE TITLE
Updated KorEXO .csv file (variable name change)

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#77]
KorEXO Software V2.3.10.0 (released Oct 2020) renamed "BGA" to "TAL." They are the same variables, just different nomenclature (Blue grean algea vs. total algea). The name change causes some errors when calling various functions from exo.py... 

I've made some changes in a branch that seem to have fixed the problem. 

-Thanks!

**Comment by dnowacki-usgs** [comment]
A PR is definitely welcome. Please test to ensure both the old and new variable names are supported. Thanks.

**Comment by dnowacki-usgs** [comment]
Closed by #84
