### ISSUE TITLE
Missing serial numbers from some EXO variables

### ISSUE THREAD

**Issue by rbales-usgs** [USGS-CMG/stglib#78]
When looking into issue #77, I noticed some exo variables were not paired with the sensor serial numbers. 
For example, Turb, T_28, and S_41 do not have the "sensor_serial_number" attribute after processing to the final .nc file. 

I made some changes to read_exo() in a feature branch. 

Dan, let me know if I should lump the edits from this issue and issue #77 into one PR. 
If you would like to make these changes on yourself, that's fine too!

Thanks!

**Comment by dnowacki-usgs** [comment]
A PR is definitely welcome! Since they are both dealing with exo improvements I'm fine with having them in the same PR if that's easier for you. Two is great, too.

**Comment by dnowacki-usgs** [comment]
Closed by #84
